### ISSUE TITLE
Editor is controllable with joystick

### ISSUE THREAD

**Issue by MyUsernamee** [ramchale/godot-multiplayer-input-sharp#2]
After installing this extension the editor is now controllable with a joystick and isn't great because when testing the game it also controls the editor.

##Steps to reproduce
Install the plugin like stated then try moving your joystick around.

I am unsure if I am doing anything wrong so please let me know if I am. Thank you for any help in advance! :)

**Comment by ramchale** [comment]
Thanks for letting me know. I'll take a look

**Comment by ramchale** [comment]
Merged a PR that should fix it. It'll probably need a recompile and project reload for the fixed code to take affect. Let me know if you're still having issues.

https://github.com/ramchale/godot-multiplayer-input-sharp/pull/3/files
